package mocks

import (
	"Pharmacy/internal/pkg/entity"

	"github.com/stretchr/testify/mock"
)

// LocalRepository is an autogenerated mock type for the LocalRepository type
type LocalRepository struct {
	mock.Mock
}

// GetLocales provides a mock function with given fields:
func (_m *LocalRepository) GetLocales() ([]entity.Local, error) {
	ret := _m.Called()

	var r0 []entity.Local
	if rf, ok := ret.Get(0).(func() []entity.Local); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Local)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocalesByComuna provides a mock function with given fields: comuna
func (_m *LocalRepository) GetLocalesByComuna(comuna string) ([]entity.Local, error) {
	ret := _m.Called(comuna)

	var r0 []entity.Local
	if rf, ok := ret.Get(0).(func(string) []entity.Local); ok {
		r0 = rf(comuna)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Local)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(comuna)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
